### ISSUE TITLE
Unused special formatting in natspec

### ISSUE THREAD

**Issue by adamgall** [fractal-framework/fractal-contracts#27]
There are quite a few places in the AccessControl natspec comments where there's some special formatting around referenced function names, eg:

```solidity
/// @dev Returns the admin role that controls `role`. See {grantRole} and {revokeRole}.
/// To change a role's admin, use {_setRoleAdmin}.
```

i believe this is because openzeppelin's docs generator replaces those with links (see: https://docs.openzeppelin.com/contracts/4.x/api/access#AccessControl-getRoleAdmin-bytes32-). we don't need to get that fancy with our docs (yet...), so for now please simplify this natspec and remove the OZ-specific formatting, etc. Make it your own.

**Comment by tbwebb22** [comment]
Submitted PR "Clean up natspec #40" to address this issue
